### ISSUE TITLE
JS9 ERROR: could not preload image(s): .....

### ISSUE THREAD

**Issue by nicolaschotard** [ericmandel/js9#35] opened 2018-02-22 14:52 UTC
@ericmandel Is there something to set up before making `js9preload.html` works and actually `Preload` the different files (`fits` and `http`) that should be displayed? 

For some reason, I cannot manage to make it work and get this `JS9 ERROR: could not preload image(s):` for all images (+ `please check the url/pathname` for local images). I've also tried on a local image taken on my computer but it doesn't work either. 

I should mention that I'm using Firefox and tried both the master branch and version `2.0.2` of `js9`, and that loading an image from the menu bar with `File -> open local file...` is working fine.

Thanks for your help!

**Comment by ericmandel** [comment] 2018-02-22 15:15
@nicolaschotard For URLs outside your web page domain, you need to be running the JS9 helper with proxy load enabled. Otherwise the web's same-origin policy will not let you display the image . With proxy load enabled, the JS9 helper will retrieve the external URL into a temp directory, so that it can now load the image from the same origin. (I see that the Preload documentation is not complete ... I'll fix that!). 

For the local files, the pathname should be relative to the web page, but should work with or without a helper. You can test this by running JS9.Load() with the same pathname in a Javascript console window once the page is loaded.

**Comment by nicolaschotard** [comment] 2018-02-22 15:27
Thanks for your quick answer @ericmandel I've just realized that pre-loading `js9Readme.png`, which is in the same directory, is working, but loading an image located in the parent directory is not. Doing that, I get the following error `could not read off-screen image data [same-origin policy violation?]`. Didn't you say that this should work for local file?

**Comment by ericmandel** [comment] 2018-02-22 15:37
Yes, this should all work, but if you are getting a same-origin error, then there is a mismatch somewhere. Are you loading your web page via a web server (localhost:// or something similar) or using the file:// URI? How are you specifying the pathname of the file you want to load?

**Comment by nicolaschotard** [comment] 2018-02-22 15:57
I'm using the file `file:///home/path/js9-2.0.2/js9preload_test.html`, and here is the content of mu `html` test file 

```<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" > 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link type="image/x-icon" rel="shortcut icon" href="./favicon.ico">
    <link type="text/css" rel="stylesheet" href="js9support.css">
    <link type="text/css" rel="stylesheet" href="js9.css">
    <script type="text/javascript" src="js9prefs.js"></script>
    <script type="text/javascript" src="js9support.min.js"></script>
    <script type="text/javascript" src="js9.js"></script>
    <script type="text/javascript" src="js9plugins.js"></script>
    <title>JS9 view</title>
  </head>
  <body onload="JS9.Preload('../js9Readme.png');">
    <table>
      <tr>
	<td>
	  <div class="JS9Menubar" data-width="600px"></div>
	  <div class="JS9" data-width="600px" data-height="600px"></div>
	  <div class="JS9Colorbar" data-width="600px"></div>
	</td>
      </tr>
      
      <tr>
      </tr>    
  </body>
</html>```

**Comment by ericmandel** [comment] 2018-02-22 16:12
Hmmm ... I used your code successfully on my Mac and on my Linux box with FF and Chrome (with correct switches). But while I was testing, FF asked me to "refresh" and after I did that (FF 52.5.1), I get the error you are seeing. So something has changed with Linux FF and the file:// URI that I need to investigate.

**Comment by nicolaschotard** [comment] 2018-02-22 16:21
I'm actually relieved that you can reproduced this error. What is exactly the difference between importing a file using the `Preload` function and doing it from the Menu with `File -> open local file...`?

**Comment by ericmandel** [comment] 2018-02-22 16:31
File -> open local uses the browser's ability to read a local file into a chunk of data called a "Blob" (this is the same functionality as drag and drop, which also works), which is then processed by JS9.  There is no same origin issue in this case. The Load and Preload routines use the standard XHR call to retrieve the file (so same origin policy does apply) and then processes the data that is retrieved.

The problem we are seeing is caused by shifting rules governing whether the file:// URI can load local files. Firefox always allowed it without doing anything special ... I guess until today. Chrome requires a special switch on the command line ... otherwise it throws the same-origin error. Safari allows the file:// URL to load local files on Sierra but apparently not on High Sierra. It's a mess.

I'll look into this today, it's going to be a problem for others as well.

**Comment by nicolaschotard** [comment] 2018-02-22 16:35
Dealing with several web browsers if usually a mess. Thanks a lot for looking into that.

**Comment by ericmandel** [comment] 2018-02-22 16:47
By the way, the problem we are seeing seems to be be a restriction on loading files that are not "underneath" the web page, when using the file:/ URI. In the Javascript console I cannot do this:
````
JS9.Load("../m13.fits")
````
but I can do this:
````
JS9.Load("m13.fits")
JS9.Load("fits/m13.fits")
````
i.e., where the FITS file is in a directory "underneath" the web page.

How would that affect your work? A public web server will not have this particular problem. When using the file:// URI locally on Linux, you might have to use Chrome or keep the files underneath the web page.  Or use the JS9 app (via Electron.js, which is Chrome underneath).

**Comment by nicolaschotard** [comment] 2018-02-22 17:05
My goal was to include a simple `js9` windows into an app that I'm developing, and which should be able to run locally (actually on a server) and work on images located at different places on this server. I was going for a page listing the images, and clickable in order to show their content in `js9`. I will see what i can do to go around this problem. Thanks for your help.

**Comment by ericmandel** [comment] 2018-02-22 17:23
If your app is running on a web server, with users visiting by loading a http:// or https:// web page, you won't have this particular problem. But you will have the problem of whether the web server itself allows access to files outside the web page domain. For security reasons, this is not a good idea: if you allow broad access to files outside the web domain, then users can retrieve anything.

One technique you can use is to make one or more links inside the web page domain to outside directories containing data files. This is pretty safe if you keep the linked-to directories clean.

**Comment by nicolaschotard** [comment] 2018-02-23 07:10
Indeed, creating a hard link inside the web domain pointing to the file I want to load is working. And it seems safe. I will go with that solution. Tanks for your help!

**Comment by ericmandel** [comment] 2018-02-23 13:07
Thinking more about this, I suspect FF is restricting access to files using the file:// URI to mimic the restrictions you will face using the http(s):// URI on a real web server: you can't beak out of the web page domain in either case. It's good for us to work out the techniques required to deal with these restrictions as we use file://, leading to fewer surprises when going public.

I'll close this issue ... let me know if you have other problems.

**Closed by ericmandel** 2018-02-23 13:07 UTC
