### ISSUE TITLE
Issues loading large multi-extension files

### ISSUE THREAD

**Issue by paruzzz** [ericmandel/js9#26] opened 2017-04-10 07:21 UTC
Hello Eric,

The website I'm working on  needs to display large multi-extension fits files which are been dynamically updated throughout the exposure time.

Whenever I'm testing it live, the JS9 plug in is waiting for the entire multi-extension file to be written completely on the hard disk (ie, for the entire exposure time), and then it takes an additional time to load it. Our files consists of an average of 100- 150 hdus. 

We are looking for a dynamic display in the JS9 plugin window which will load the latest extension available.

Please help with this issue.

**Comment by ericmandel** [comment] 2017-04-10 11:41
@paruzzz Have you looked at the JS9.RefreshImage() public routine? This routine allows you to re-display an image with new data that can be supplied in various formats. Once you have sent the newly updated extension to the web page, you can then call RefreshImage to display it. This is supposed to be fast enough for real-time updates and is being used in some telescope control systems.

But there still remains the question of moving the updated data to the web page. How do you want this to happen? Server side push or client side pull? And do you want all of the data saved in the client or only the latest extension? JS9.RefreshImage() does not care how any of this happens, but it also currently assumes that you will do the transfer yourself, according to the needs of your application. 

If you let me know how the transfer is supposed to be initiated and controlled, I'll try to help more. There are plenty of options to think about.

**Comment by paruzzz** [comment] 2017-04-11 05:10
Dear Eric,

We are moving the latest update from data machine to web server via rsync
and the latest filename is passed on via javascript on the web page.

can you tell me how to use the JS9.RefeshImage() routine with the inputs we
have and then point to the last extension (does JS9 has a public variable
like hdu length??)

Thank you for your prompt replies.

**Comment by ericmandel** [comment] 2017-04-11 14:06
@paruzzz JS9.RefreshImage() assumes you have the new FITS data transferred into the browser already. In a typical real-time application, you would have a data acquisition worker in your web page retrieving the data and passing it onto JS9.RefreshImage().

In your case, you have a re-written FITS file on disk. If you want to display its last extension without transferring the entire file to the browser, you probably need to extract that last section on the server side into a new file, and tell JS9 to load that file. In other words, use Linux tools to figure out the last FITS extension, generate a FITS file containing only that extension,  and then load that file containing only the one extension.

For example, if you have the HEASARC ftools package installed:

https://heasarc.gsfc.nasa.gov/lheasoft/ftools/

you can use the fstruct program to determine the extensions in the FITS file:
````
eric% fstruct colinfo=no ~/data/mef.fits
  No. Type     EXTNAME      BITPIX Dimensions(columns)      PCOUNT  GCOUNT
 
   0  PRIMARY                 16     0                           0    1
   1  IMAGE    SCI           -32     270 263                     0    1
   2  IMAGE    ERR           -32     270 263                     0    1
   3  IMAGE    DQ             16     270 263                     0    1
   4  IMAGE    SAMP           16     270 263                     0    1
   5  IMAGE    TIME          -32     270 263                     0    1
````
A few lines of awk and grep will tell you the last extension number in the file. Then use fcopy to generate a new FITS file containing only the last extension:
````
eric% ftcopy copyall=no clobber=yes ~/data/mef.fits'[5]' foo.fits
eric% fstruct colinfo=no foo.fits
  No. Type     EXTNAME      BITPIX Dimensions(columns)      PCOUNT  GCOUNT
 
   0  PRIMARY                -32     270 263                     0    1
````
Then send the filename foo.fits to JS9, (possible close the previously displayed file if you don't need it any longer), and open the new one.

If this is not a good solution, tell me more and I will try to help.

**Comment by paruzzz** [comment] 2017-04-11 16:28
I've tried this option using astropy, extracting the last extension and
displaying it in js9 as a single fits file. The issue with that is, astropy
if waiting for the for to be completed (it shows file truncated error) ,
and after the entire multi extension is written, it points to the last
extension. In short, only the first and last hdu's are displayed on the js9
plug in.

**Comment by ericmandel** [comment] 2017-04-11 19:53
I don't know much about astropy, but it sounds like you need to close and then reopen the FITS file every time you are going to extract the last extension. Python experts might be more help here.

**Comment by ericmandel** [comment] 2017-04-20 21:14
@paruzzz Are you making progress on this problem? Can I help? Or perhaps its been solved and we can close this issue?

**Comment by paruzzz** [comment] 2017-04-28 11:27
Dear Eric,

I've been trying to make progress with the method you suggested earlier.
I've managed to populate the latest fits files in the web directory
and the same file gets updated every 0.5 seconds. (the file is deleted
and the new file is created). The JS9.Load is not able to load (load ,
close and load next) the new image is 0.5 seconds (its an observation)
and hence it waits until the file updating stops. Effectively, it
displays only the first and last files. Can you help me find a
solution to this?

**Comment by ericmandel** [comment] 2017-04-29 13:23
@paruzzz Can you show me the routine you wrote that calls JS9.Load() on the client side? Are you calling it every few seconds? How fast to you want the refresh to happen? How are you synchronizing with the server?

JS9.Load is asynchronous, so you may be running into unexpected race conditions. Also, you have to close the image before calling JS9.Load() or else it will not actually perform the load, it will only display the current image. In general, (but depending on what you want to do), I would recommend using an XHR request to retrieve the new file and then pass this new file to JS9.RefreshImage().

It might be easier to exchange code  and ideas via email at this point (eric@cfa.harvard.edu). But send  or show me some code, tell me more about how you want the refresh to happen, and I will try to help.

**Comment by paruzzz** [comment] 2017-05-01 09:23
//init() is the on load function.

function init()
{
               JS9.Load('VIC/vic.fits',{colormap:"grey", zoom:"to fit",
display:"JS9"});
               JS9.Load('WFS/wfs.fits',{colormap:"grey", zoom:"to fit",
display:"myJS9", scale:"histeq"});
}
function wfs_loop()
{
JS9.CloseImage({display:'myJS9'});
//console.log("loading WFS new image: ", wfsimages[wfsimageIndex]);
JS9.Load('WFS/wfs.fits',{colormap:"grey", zoom:"to fit", display:"myJS9",
scale: "histeq"});
//JS9.RefreshImage('wfs.fits');
window.setTimeout(function(){wfs_loop();},400);
}

function vic_loop()
{
               JS9.CloseImage({display:'JS9'});
               //console.log("loading VIC new image: vic.fits");
               JS9.Load('VIC/vic.fits',{colormap:"grey", zoom:"to fit",
display:"JS9"});
               //JS9.RefreshImage('vic.fits');
               window.setTimeout(function(){vic_loop();},400);
}
function reload_image1()
{
var now= new Date();
document.images['img-circle'].src='Telemetry/gradient.png?'+now.getTime();
timeoutID=setTimeout('reload_image1()',500);

}
function reload_image2()
{
var now= new Date();
//var i =0;
document.images['img-circle1'].src='Telemetry/gradient1.png?'+now.getTime();
//var old= document.images['img-circle1'].src;
timeoutID=setTimeout('reload_image2()',500);

}


$(document).ready(function()
{
               wfs_loop();
                vic_loop();
                reload_image1();
                reload_image2();

});


I want the image to be refreshed every 0.5 seconds. Both files wfs.fits and
vic.fits are getting updated every 0.5 seconds. So even though, effectively
the filename is the same, the content inside the file is changing every 0.5
seconds. This is achieved by a parallel python script which uses the
astropy libraries.

The synching from Data machine to the webserver is done using rsync
routines.

**Comment by ericmandel** [comment] 2017-05-01 20:32
@paruzzz  I suspect that the JS9.Close() call is interacting badly with the asynchronous JS9.Load() call. If JS9.Load() takes more than .4 seconds, the next JS9.Close() call will happen before JS9.Load() completes, and this will break the close/display  cycle.

I've written some test code that does work properly (with one big caveat, see below). It uses XHR to retrieve the new data as a blob and then just calls JS9.Refresh() only when the retrieval is complete. Doing it this way means you don't have to call JS9.Close, because you are refreshing the same image over and over.

The big caveat is that JS9 will throw an error is the retrieved blob is not a complete FITS file. The problem is that the update via rsync might not be finished when the periodic retrieval is called, and you therefore can retrieve a partial FITS file, which will cause an error when JS9 tries to process it. I added a very high level check to guess whether the FITS file is valid, but it's not perfect.

Do you have a way of guaranteeing that the rsync'ed FITS file is complete and ready to be loaded? That will be an important problem to resolve. On my end, I need to try to understand how to handle that error better, but I don't how to do that yet.

/* global JS9 */

var vicimage = "../tmp/VIC/vic.fits";
var wfsimage = "../tmp/WFS/wfs.fits";

// initial load of images
// eslint-disable-next-line no-unused-vars
function vw_init()
{
    JS9.Load(vicimage, {colormap:"cool", zoom:"to fit"}, {display:"JS9"});
    JS9.Load(wfsimage, {colormap:"heat"}, {display:"myJS9"});
}

function do_loop(url, id, cb, timeout){
    var xhr = new XMLHttpRequest();
    xhr.open("GET", url, true);
    xhr.responseType = "blob";
    xhr.onload = function(){
	var blob;
        if( this.readyState === 4 ){
	    if( this.status === 200 || this.status === 0 ){
	        blob = new Blob([this.response]);
		// is this a valid FITS file?
		if( blob.size > 0 && blob.size % 2880 === 0 ){
		    try{
			// fresh current display
			JS9.RefreshImage(blob, {onrefresh: function(){
			    window.setTimeout(function(){cb();},timeout);
			}}, {display: id});
		    } catch(e){
			window.setTimeout(function(){cb();},timeout);
		    }
		} else {
		    window.setTimeout(function(){cb();},timeout);
		}
	    } else {
		window.setTimeout(function(){cb();},timeout);
	    }
	}
    };
    xhr.onerror = function() {
	window.setTimeout(function(){cb();},timeout);
    };
    xhr.send();
}

// eslint-disable-next-line no-unused-vars
function vic_loop(){
    do_loop(vicimage, "JS9", vic_loop, 400);
}

// eslint-disable-next-line no-unused-vars
function wfs_loop(){
    do_loop(wfsimage, "myJS9", wfs_loop, 400);
}

$(document).ready(function(){
    // change error handler so that it does not throw an error
    // this does not work, for some reason, though it should!
    JS9.fits.options.error = function(s){console.log("LOOPERROR: " + s)};
    // load initial files
    vw_init();
});

**Comment by ericmandel** [comment] 2017-08-11 01:05
@paruzzz Is there anything I can do to help you? Should we close this issue?

**Comment by paruzzz** [comment] 2017-08-11 05:35
Thank you Eric. We can close this issue.

**Closed** 2017-08-11 11:33 UTC
