### ISSUE TITLE
Spinner when loading image

### ISSUE THREAD

**Issue by pepric** [ericmandel/js9#58] opened 2019-05-09 16:47 UTC
Hi,
I have noticed that, when I try to load an image by using File-->open local file , the waiting gif does not appear, while it works well when I use a hyperlink. Is it a very minor bug or I'm wrong in something? 

Thanks
G

**Comment by ericmandel** [comment] 2019-05-09 17:02
Right, the problem is that system's local file facility retrieves the file as a blob before JS9 code comes into play, and then immediately calls the JS9 blob processing code, without ever relinquishing the CPU so that the event loop can start the spinner ... the URL fetch code does, of course, give up the CPU while the file is being retrieved. A quick look at the open local code warns me that it will get messy to add the needed timeout, but I'll give it some more concentrated thought ...

**Comment by pepric** [comment] 2019-05-09 17:06
Thank you very much

**Comment by ericmandel** [comment] 2019-05-09 17:14
I'll re-open this issue so that I can close it with a definitive answer ...

**Comment by ericmandel** [comment] 2019-05-09 23:17
@pepric I had a closer look at this problem and it turns out that there is a nice, obvious place to start the spinner manually. The corrected code should make it into GitHub in the next update.  Thanks for pointing it out!

**Closed by ericmandel** 2019-05-09 23:17 UTC
