### ISSUE TITLE
Multi-Extension fits file display.

### ISSUE THREAD

**Issue by paruzzz** [ericmandel/js9#25] opened 2017-01-17 09:41 UTC
Hi,

I'm pretty new to JS9 and I want to use it in my website (server side). I've multi extension fits cubes and I want to play each extension for some time and then switch to the next extension.

ie. if my multi-extensional fits file has 7 extensions, I want to preload the window with the primary extension and then play through 1 to 7 with a time delay.

The entire fits file has to be refreshed whenever there is an update to the file or a new file added. For this, I think I can use   JS9.RefreshImage() and then again play through the extensions.

Can you please suggest me how I can do this using JS9.

**Comment by ericmandel** [comment] 2017-01-17 13:45
The JS9 Public Access routine JS9.DisplayExtension(extid) is what you want. Here extid can either be the extension number or the extension name (where present). You can play with this by loading one of your extension files into JS9 and then calling the routine in the JavaScript Console.

How you call JS9.DisplayExtension() depends on your user interface. I presume you would have a Start/Stop button which would call  window.setTimeout(), which in turn would repeatedly call JS9.DisplayExtension() until the Stop is clicked, ext. Inside the loop, you keep track of when to wrap back to the first extension, etc.

When a new file is loaded, you probably want to set the extid back to 1. But other than that, you don't have to do anything special, because, by default, JS9.DisplayExtension() will act on the currently displayed image, i.e. it will just display the next extension of the newly displayed image.

One way to package all of this is to create a JS9 plugin, which will allow you to define a callback function to execute when a new image is loaded, in case you need to do something special. See http://js9.si.edu/js9/js9plugins.html and the js9/plugins/plugintest.js() code example.

**Comment by paruzzz** [comment] 2017-01-19 10:25
The website that I'm building requires two JS9 plugins for displaying two types of FITS images.

1. The first plugin goes through 4 FITS images at a delay of 500 milliseconds.
2. The second plugin plays through the different extensions in a single multi-extension FITS file.

Both the windows have to be refreshed when there is a new FITS image file or the image file gets updated.

Please find the way I'm using the APIs in the below code snippet.
_________________________________________________________________________________________
<script type="text/javascript">
function init()
{ JS9.Preload("wfs_ccd_CCD39_UV_o_20160628_093354.775544_0514.fits",{colormap:"grey", zoom:"16", display:"JS9"},"pointing_VIC_Si_o_20160809_110517.069884.fits",{colormap:"grey",  display:"myJS9"} ); 
//"pointing_VIC_Si_o_20160809_110517.069884.fits",{colormap:"grey",  display:"myJS9"}
}

function img_ref()
{
JS9.Load("pointing_VIC_Si_o_20160809_110517.069884.fits",{colormap:"grey", display:"myJS9"});
JS9.Load("wfs_ccd_CCD39_UV_o_20160628_093354.775544_0514.fits",{colormap:"grey", zoom:"16", display:"JS9"});
return true
}

function cube_loop()
{
for(i=0; i<8; i++) //We've to pass the variable here
	{
	sleep(500);
	//JS9.DisplayExtension(i,{display:"myJS9"});
		
	} return true
}
function wfs_loop()
{
	JS9.Load("wfs_ccd_CCD39_UV_o_20160628_093354.775544_0514.fits",{colormap:"grey", zoom:"16", display:"JS9"});
	sleep(500);
	JS9.CloseImage();
	JS9.Load("wfs_ccd_CCD39_UV_o_20160628_093354.777020_0515.fits",{colormap:"grey", zoom:"16", display:"JS9"});
	sleep(500);
	JS9.CloseImage();
	JS9.Load("wfs_ccd_CCD39_UV_o_20160628_093354.778483_0516.fits",{colormap:"grey", zoom:"16", display:"JS9"});
	sleep(500);
	JS9.CloseImage();
	JS9.Load("wfs_ccd_CCD39_UV_o_20160628_093354.780194_0517.fits",{colormap:"grey", zoom:"16", display:"JS9"});
	sleep(500);
	JS9.CloseImage();
	return true
}

function sleep(milliseconds) {
  var start = new Date().getTime();
  for (var i = 0; i < 1e7; i++) {
    if ((new Date().getTime() - start) > milliseconds){ return milliseconds;
      break;
    }
  }
}

</script>

	<div class="JS9Menubar" id="JS9"></div>
	<div class="JS9" id="JS9"></div>
	<div style= "margin-left: 500px;">
	</div>
	 <div id="myTabsContainer">
	<div id="js9tabs" class="indentmenu">
	</div> 
	</div> 

</br> </br> 
	<div class="JS9Menubar" id="myJS9"></div>
	<div class="JS9" id="myJS9"></div>
	<div style= "margin-left: 200px;">
	</div>   
______________________________________________________________________________________ 
**Whenever I'm calling the loop functions, the JS9 plugin is moving between the first image and last image. Its not displaying the images in between. (There by its not giving a moving feeling.)**

The Size of WFS image =6kB each.
Multi-extension cube=33MB.

Can you please tell me what is wrong in the API call or implementation.

**Comment by ericmandel** [comment] 2017-01-19 14:27
The problem is that JS9.Load() is an asynchronous call, and all of your image loads are completing before you can display the extensions. We deal with the asynchronous nature of web programming by using callbacks. In this case, you would call JS9.Load and specify an onload callback to display the extensions.

Also, you should use setTimeout instead of blocking the web page while waiting for the time to expire.

Finally, it would be easier if the display extension routine loaded the next image once all of the extensions were displayed, instead of trying to load all images at the start.

Here is a web page that shows these ideas in practice.  You can modify it to load your images and display the extensions. It works on my test cases … with the usual caveats about it being a demo.

````
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" > 
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link type="image/x-icon" rel="shortcut icon" href="./favicon.ico">
  <link type="text/css" rel="stylesheet" href="js9support.css">
  <link type="text/css" rel="stylesheet" href="js9.css">
  <link type="text/css" rel="stylesheet" href="plugins/plugintest.css">
  <script type="text/javascript" src="js9support.js"></script>
  <script type="text/javascript" src="js9.js"></script>
  <script type="text/javascript" src="js9plugins.js"></script>
</head>
<body>
<div class="JS9Menubar"></div>
<div class="JS9"></div>
<div style="margin-top: 2px;">
<div class="JS9Colorbar"></div>

<script>
var timeout = 2000;
var extMin = 1;
var extMax = 5;
var extIndex = extMin;
var imageIndex = 0;
var images = [
  "../data/mef.fits",
  "../data/mef2.fits",
  "../data/mef3.fits"
];
var cmaps = [
  "cool",
  "heat",
  "viridis"
];

function displayExtensions(){
    if( extIndex <= extMax ){
        console.log("displaying extension: ", extIndex);
        JS9.DisplayExtension(extIndex++);
        window.setTimeout(function(){
            displayExtensions();
        }, timeout);
    } else {
        if( imageIndex < images.length ){
            extIndex = extMin;
            console.log("loading new image: ", images[imageIndex]);
            JS9.Load(images[imageIndex++], 
                   {colormap: cmaps[imageIndex], onload: displayExtensions});
        }
    }
}

$(document).ready(function(){
    JS9.Load(images[imageIndex++],
             {colormap: cmaps[imageIndex], onload: displayExtensions});
});
</script>
</body>
</html>
````

**Comment by paruzzz** [comment] 2017-01-23 11:31
Thank you Eric for the prompt replies.
In the website I'm trying to make, there are two JS9 displays (id- "myJS9" and "JS9").
I've to continuously loop the images for  infinite duration.
How do I close an image by specifying the display?
Every Time I'm calling JS9.CloseImage(), only displayid-"JS9" is getting closed.
Hence the browser is eventually running out of memory. The errors I'm getting after 5 mins is,

>### Uncaught RangeError: Invalid typed array length
    at new Int8Array (native)
    at Tb (http://192.168.13.129/js9-master/js9support.min.js:510:3198)
    at enlargeMemory (http://192.168.13.129/js9-master/js9support.min.js:508:21939)
    at Function.dynamicAlloc [as alloc] (http://192.168.13.129/js9-master/js9support.min.js:508:6303)
    at _sbrk (http://192.168.13.129/js9-master/js9support.min.js:508:475635)
    at wy (http://192.168.13.129/js9-master/js9support.min.js:526:81591)
    at Gc (http://192.168.13.129/js9-master/js9support.min.js:518:21792)
    at ccallFunc (http://192.168.13.129/js9-master/js9support.min.js:508:8114)
    at Object.Module.getFITSImage (http://192.168.13.129/js9-master/js9support.min.js:536:11108)
    at Object.Module.handleFITSFile (http://192.168.13.129/js9-master/js9support.min.js:536:15969)

RangeError: Source is too large
    at Int8Array.set (native)
    at Object.read (http://192.168.13.129/js9-master/js9support.min.js:508:412302)
    at Object.read (http://192.168.13.129/js9-master/js9support.min.js:508:447909)
    at Object.doReadv (http://192.168.13.129/js9-master/js9support.min.js:508:468343)
    at ___syscall145 (http://192.168.13.129/js9-master/js9support.min.js:508:532092)
    at Array.Hw (http://192.168.13.129/js9-master/js9support.min.js:526:27420)
    at _w (http://192.168.13.129/js9-master/js9support.min.js:526:33216)
    at Array.Pi (http://192.168.13.129/js9-master/js9support.min.js:513:93460)
    at ji (http://192.168.13.129/js9-master/js9support.min.js:513:70946)
    at uu (http://192.168.13.129/js9-master/js9support.min.js:528:80159)
js9support.min.js:508 RangeError: Source is too large
    at Int8Array.set (native)
    at Object.read (http://192.168.13.129/js9-master/js9support.min.js:508:412302)
    at Object.read (http://192.168.13.129/js9-master/js9support.min.js:508:447909)
    at Object.doReadv (http://192.168.13.129/js9-master/js9support.min.js:508:468343)
    at ___syscall145 (http://192.168.13.129/js9-master/js9support.min.js:508:532092)
    at Array.Hw (http://192.168.13.129/js9-master/js9support.min.js:526:27420)
    at _w (http://192.168.13.129/js9-master/js9support.min.js:526:33216)
    at Array.Pi (http://192.168.13.129/js9-master/js9support.min.js:513:93460)
    at ji (http://192.168.13.129/js9-master/js9support.min.js:513:70946)
    at uu (http://192.168.13.129/js9-master/js9support.min.js:528:80159)
iroboao.php:236 displaying extension:  1
iroboao.php:265 loading new image:  wfs_ccd_CCD39_UV_o_20160628_093354.777020_0515.fits
iroboao.php:236 displaying extension:  2
js9.min.js:293 Uncaught Error: no FITS HDUs found for displayExtension()
    at Object.a.error (http://192.168.13.129/js9-master/js9.min.js:293:202)
    at a.Image.displayExtension (http://192.168.13.129/js9-master/js9.min.js:75:3)
    at Object.string.a.Image.(anonymous function).a.(anonymous function) [as DisplayExtension] (http://192.168.13.129/js9-master/js9.min.js:414:194)
    at displayExtensions (http://192.168.13.129/iroboao.php:237:13)
    at http://192.168.13.129/iroboao.php:239:13
js9support.min.js:536 RangeError: Source is too large
    at Int8Array.set (native)
    at Object.read (http://192.168.13.129/js9-master/js9support.min.js:508:412302)
    at Object.read (http://192.168.13.129/js9-master/js9support.min.js:508:447909)
    at Object.doReadv (http://192.168.13.129/js9-master/js9support.min.js:508:468343)
    at ___syscall145 (http://192.168.13.129/js9-master/js9support.min.js:508:532092)
    at Array.Hw (http://192.168.13.129/js9-master/js9support.min.js:526:27420)
    at _w (http://192.168.13.129/js9-master/js9support.min.js:526:33216)
    at Array.Pi (http://192.168.13.129/js9-master/js9support.min.js:513:93460)
    at ji (http://192.168.13.129/js9-master/js9support.min.js:513:70946)
    at uu (http://192.168.13.129/js9-master/js9support.min.js:528:80159)
js9support.min.js:508 RangeError: Source is too large
    at Int8Array.set (native)
    at Object.read (http://192.168.13.129/js9-master/js9support.min.js:508:412302)
    at Object.read (http://192.168.13.129/js9-master/js9support.min.js:508:447909)
    at Object.doReadv (http://192.168.13.129/js9-master/js9support.min.js:508:468343)
    at ___syscall145 (http://192.168.13.129/js9-master/js9support.min.js:508:532092)
    at Array.Hw (http://192.168.13.129/js9-master/js9support.min.js:526:27420)
    at _w (http://192.168.13.129/js9-master/js9support.min.js:526:33216)
    at Array.Pi (http://192.168.13.129/js9-master/js9support.min.js:513:93460)
    at ji (http://192.168.13.129/js9-master/js9support.min.js:513:70946)
    at uu (http://192.168.13.129/js9-master/js9support.min.js:528:80159)
js9support.min.js:536 Uncaught abort({}) at Error
    at jsStackTrace (http://192.168.13.129/js9-master/js9support.min.js:508:20834)
    at stackTrace (http://192.168.13.129/js9-master/js9support.min.js:508:21017)
    at abort (http://192.168.13.129/js9-master/js9support.min.js:536:6627)
    at ___syscall145 (http://192.168.13.129/js9-master/js9support.min.js:508:532186)
    at Array.Hw (http://192.168.13.129/js9-master/js9support.min.js:526:27420)
    at _w (http://192.168.13.129/js9-master/js9support.min.js:526:33216)
    at Array.Pi (http://192.168.13.129/js9-master/js9support.min.js:513:93460)
    at ji (http://192.168.13.129/js9-master/js9support.min.js:513:70946)
    at uu (http://192.168.13.129/js9-master/js9support.min.js:528:80159)
    at Vh (http://192.168.13.129/js9-master/js9support.min.js:513:33818)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information. 

`<html>

<head>
	<link href="iroboao_new.css" rel="stylesheet" type="text/css" media="screen"/>	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" > 
	<meta name="viewport" content="width=device-width, initial-scale=1" >
 	 <link type="text/css" rel="stylesheet" href="js9-master/js9support.css">
  	<link type="text/css" rel="stylesheet" href="js9-master/js9.css">
 	 <script type="text/javascript" src="js9-master/js9support.min.js"></script>
 	 <script type="text/javascript" src="js9-master/js9.min.js"></script>
 	 <script type="text/javascript" src="js9-master/js9plugins.js"></script>
	<script type="text/javascript" src="js9-master/plugins/core/menubar.js"></script>
  	<script type="text/javascript" src="js9-master/plugins/core/info.js"></script>
</head>

<body onload= "init();">
<script type="text/javascript">
function init()
{ JS9.Preload("wfs_ccd_CCD39_UV_o_20160628_093354.775544_0514.fits",{colormap:"grey", zoom:"16", display:"myJS9"},"pointing_VIC_Si_o_20160809_110517.069884.fits",{colormap:"grey",  display:"JS9"} ); 
//"pointing_VIC_Si_o_20160809_110517.069884.fits",{colormap:"grey",  display:"myJS9"}
}

function img_ref()
{ //A function for testing only. Refeshes the image displays.
JS9.Load("pointing_VIC_Si_o_20160809_110517.069884.fits",{colormap:"grey", display:"JS9"});
JS9.Load("wfs_ccd_CCD39_UV_o_20160628_093354.775544_0514.fits",{colormap:"grey", zoom:"16", display:"myJS9"});
return true
}

var timeout = 500;
var extMin = 0;
var extMax = 7;
var extIndex = extMin;
var imageIndex = 0;
var wfsimageIndex=0;
var images = [
  "pointing_VIC_Si_o_20160809_110517.069884.fits"
];
var wfsimages= [
"wfs_ccd_CCD39_UV_o_20160628_093354.775544_0514.fits",
"wfs_ccd_CCD39_UV_o_20160628_093354.777020_0515.fits",
"wfs_ccd_CCD39_UV_o_20160628_093354.778483_0516.fits",
"wfs_ccd_CCD39_UV_o_20160628_093354.780194_0517.fits"
];

var cmaps = [
  "grey" 
];

function displayExtensions(){
    if( extIndex <= extMax ){
        console.log("displaying extension: ", extIndex);
        JS9.DisplayExtension(extIndex++);
        window.setTimeout(function(){
            displayExtensions();
        }, timeout);
    } else {
        if( imageIndex < images.length ){
            extIndex = 0;
            console.log("loading new image: ", images[0]);
            JS9.Load(images[0], 
                   {colormap: cmaps[imageIndex], onload: displayExtensions});
        }
	if(imageIndex=images.length)
	{
	JS9.CloseImage();
	imageIndex=0;
	}
    }
//displayExtensions(); FIND A WAY TO KEEP PLAYING IN LOOP
}




function wfs_loop()
{
	
	if(wfsimageIndex<(wfsimages.length))
	{
		console.log("loading new image: ", wfsimages[wfsimageIndex]);
		JS9.Load(wfsimages[wfsimageIndex++],{colormap:"grey", zoom:"16", display:"myJS9"});
		window.setTimeout(function(){wfs_loop();},timeout);
		//sleep(500);
		
	}
	if( wfsimageIndex >= wfsimages.length )
			{
			wfsimageIndex=0;
			console.log("loading new image: ", wfsimages[wfsimageIndex]);
			JS9.Load(wfsimages[wfsimageIndex],{colormap:"grey", zoom:"16", display:"myJS9", onload:wfs_loop});
			}
	
}


</script>

	<div class="JS9Menubar" id="JS9"></div>
	<div class="JS9" id="JS9"></div>
	<div style= "margin-left: 500px;">
	</div>
	 <div id="myTabsContainer">
	<div id="js9tabs" class="indentmenu">
	</div> 
	</div> 

</br> </br> 
	<div class="JS9Menubar" id="myJS9"></div>
	<div class="JS9" id="myJS9"></div>
	<div style= "margin-left: 200px;">
	</div>   
	 <div id="myTabsContainerone">
	<div id="myjs9tabs" class="indentmenu">
	</div>
	</div>   
<script>

$(document).ready(function(){
JS9.Load(images[imageIndex],{colormap:cmaps[imageIndex],display:"JS9",onload:displayExtensions});
JS9.Load(wfsimages[wfsimageIndex],{colormap:"grey", zoom:"16", display:"myJS9", onload:wfs_loop});

});

setInterval(function(){
JS9.Load(images[imageIndex],{colormap:cmaps[imageIndex],display:"JS9",onload:displayExtensions});
JS9.Load(wfsimages[wfsimageIndex],{colormap:"grey", zoom:"16", display:"myJS9", onload:wfs_loop});

},5000);
</script>
</div>
<footer id="footer">
<center>  Copyright © <a href = "http://www.iucaa.in/">IUCAA </a> </center>
</footer>
</br></br> </br> </br>
</body>
</html>
`

**Comment by ericmandel** [comment] 2017-01-23 12:36
All of the JS9 public access routines take an optional argument to specify the display. To close both displays, call JS9.CloseImage() twice:
````
JS9.CloseImage({display: 'JS9'});
JS9.CloseImage({display: 'myJS9'});
````

**Comment by ericmandel** [comment] 2017-01-23 14:35
To loop on extensions, make this change to the code above:
````
function displayExtensions(){
    if( extIndex <= extMax ){
        console.log("  displaying extension: ", extIndex);
        JS9.DisplayExtension(extIndex++);
        window.setTimeout(function(){
            displayExtensions();
        }, timeout);
    } else {
        if( imageIndex >= images.length ){
          imageIndex = 0;
        }
        extIndex = extMin;
        console.log("loading image: ", images[imageIndex]);
        JS9.CloseImage();
        JS9.Load(images[imageIndex++], 
                {colormap: cmaps[imageIndex], onload: displayExtensions});
    }
}
````
On Chrome, I've been running a continuous 1/2 second loop displaying extensions from a list of images for more than an hour, with no memory problems. In fact, I don't see any increase in use of Chrome memory at all. But .... I suggest we continue debugging through email:
````
eric@cfa.harvard.edu
````
Please email me your code and make your FITS files available somewhere.

**Comment by ericmandel** [comment] 2017-01-24 13:30
Yesterday and I found and fixed two memory leaks in JS9. (Yes, even though it’s javascript, memory can leak when using emscripten to translate C libraries such as cfitsio — there is a heap used by the translated code for memory allocation and deallocation). I have updated GitHub with the new code. 

Last night I ran a continuous test of loading images and displaying extensions for 10 hours without a problem. But looking at Chrome memory usage, I see it increasing very slowly. This means that eventually the browser will hit the Chrome 4Gb limit on each tab and crash, as you saw earlier. I don’t see anywhere in the JS9 code that is allocating memory on the emscripten heap, so its possible that this is a Chrome leak. But it’s hard to find.

So my question is: do you need to run your application for an infinite amount of time? If not, I suggest you try your application using the latest version of JS9 from GitHub and let me know if it works well enough. If you do need to run forever, we’ll have to think about how to attack the remaining leaks.

**Comment by paruzzz** [comment] 2017-01-25 09:42
Dear Eric,

I tested the updated JS9 package from github but running 7 dimensional
multidimensional fits image in loop. It worked fine for 5 mins and then
chrome crashed with memory leakage.

Initial error were from cfitsio.js and then  it shows " Google chrome ran
out of memory when trying to display webpage."

**Comment by paruzzz** [comment] 2017-01-25 10:04
These are the errors with the updated package...


RangeError: Source is too large
    at Int8Array.set (native)
    at Object.read (http://192.168.13.129/js9/js9support.min.js:508:412302)
    at Object.read (http://192.168.13.129/js9/js9support.min.js:508:447909)
    at Object.doReadv (http://192.168.13.129/js9/js9support.min.js:508:468343)
    at ___syscall145 (http://192.168.13.129/js9/js9support.min.js:508:532092)
    at Array.Jw (http://192.168.13.129/js9/js9support.min.js:526:27420)
    at ax (http://192.168.13.129/js9/js9support.min.js:526:33216)
    at Array.Qi (http://192.168.13.129/js9/js9support.min.js:513:93460)
    at ki (http://192.168.13.129/js9/js9support.min.js:513:70946)
    at wu (http://192.168.13.129/js9/js9support.min.js:528:80159)
js9support.min.js:508 


Uncaught Error: no FITS HDUs found for displayExtension()
    at Object.a.error (http://192.168.13.129/js9/js9.min.js:298:417)
    at a.Image.displayExtension (http://192.168.13.129/js9/js9.min.js:75:115)
    at Object.string.a.Image.(anonymous function).a.(anonymous function) [as DisplayExtension] (http://192.168.13.129/js9/js9.min.js:419:434)
    at displayExtensions (http://192.168.13.129/iroboao.php:237:13)
    at http://192.168.13.129/iroboao.php:239:13

js9support.min.js:536 Uncaught abort({}) at Error
    at jsStackTrace (http://192.168.13.129/js9/js9support.min.js:508:20834)
    at stackTrace (http://192.168.13.129/js9/js9support.min.js:508:21017)
    at abort (http://192.168.13.129/js9/js9support.min.js:536:6720)
    at ___syscall145 (http://192.168.13.129/js9/js9support.min.js:508:532186)
    at Array.Jw (http://192.168.13.129/js9/js9support.min.js:526:27420)
    at ax (http://192.168.13.129/js9/js9support.min.js:526:33216)
    at Array.Qi (http://192.168.13.129/js9/js9support.min.js:513:93460)
    at ki (http://192.168.13.129/js9/js9support.min.js:513:70946)
    at wu (http://192.168.13.129/js9/js9support.min.js:528:80159)
    at Wh (http://192.168.13.129/js9/js9support.min.js:513:33818)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by ericmandel** [comment] 2017-01-25 12:17
Please use js9support.js instead of js9support.min.js, so that we can see real locations in the stacktrace. Do I have the FITS data file that caused this error in the package you sent yesterday?

**Comment by paruzzz** [comment] 2017-01-25 12:24
Yes. You've.

**Comment by ericmandel** [comment] 2017-01-25 12:54
OK, thanks, I'll run my test setup with your FITS files and see if there is a difference. If you run your won setup using js9.js and js9support.js instead of the minimized files, we'll both get some good data.

**Comment by ericmandel** [comment] 2017-01-25 13:46
I’ve been displaying the extensions in your pointing_VIC_Si_o_20160809_110517.069884.fits file in a loop for 20 minutes, without any increased memory usage. I append the script I am using, which you should try (adjusting the pathnames of the file or files).

Before we go further, can you please verify that you are not accidentally using the old js9 support files? Chrome is very aggressive in how it caches files, and you might have to manually empty the cache in order to pick up the new js9 files.

````
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" > 
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link type="image/x-icon" rel="shortcut icon" href="./favicon.ico">
  <link type="text/css" rel="stylesheet" href="js9support.css">
  <link type="text/css" rel="stylesheet" href="js9.css">
  <link type="text/css" rel="stylesheet" href="plugins/plugintest.css">
  <script type="text/javascript" src="js9support.js"></script>
  <script type="text/javascript" src="js9.js"></script>
  <script type="text/javascript" src="js9plugins.js"></script>
</head>
<body>
<div class="JS9Menubar"></div>
<div class="JS9"></div>
<div style="margin-top: 2px;">
<div class="JS9Colorbar"></div>

<script>
var doloop = 100;
var doinfinite = true;
var dorepeat = true;
var nimages = 0;
var timeout = 500;
var extMin = 1;
var extMax = 7;
var extIndex = extMin;
var imageIndex = 0;
var images = [
  "../data/xmef.fits",
  "../data/xmef2.fits",
  "../data/xmef3.fits"
];
var cmaps = [
  "cool",
  "heat",
  "viridis"
];

function displayExtensions(){
    if( extIndex <= extMax || dorepeat ){
        if( extIndex > extMax ){
          extIndex = extMin;
        }      
        if( dorepeat || !doinfinite ){
          console.log("  displaying extension: ", extIndex);
        }
        JS9.DisplayExtension(extIndex++);
        window.setTimeout(function(){
            displayExtensions();
        }, timeout);
    } else {
        if( imageIndex >= images.length ){
          if( doinfinite || (doloop-- >= 0) ){
	      imageIndex = 0;
          } else {
              return;
          }
        }
        extIndex = extMin;
        console.log("loading image %s: %s", nimages++, images[imageIndex]);
        JS9.CloseImage();
        JS9.Load(images[imageIndex++], 
                {colormap: cmaps[imageIndex], onload: displayExtensions});
    }
}

$(document).ready(function(){
    JS9.Load(images[imageIndex++],
             {colormap: cmaps[imageIndex], onload: displayExtensions});
});
</script>
</body>
</html>

````

**Comment by paruzzz** [comment] 2017-01-31 10:14
Thank you Eric for your support.

The memory leak got fixed and the website worked with the latest updation
of JS9  and disabling of cache.

Now can you please help me with how I can display a fits file (randomly
generated) which is outside the html directory. What changes should I do to
the JS9 settings?

-Parvathi S

**Comment by ericmandel** [comment] 2017-01-31 13:31
You can load FITS files using JS9.Load(), supplying a pathname relative to the web page's directory:
````
JS9.Load("../tmp/test/foo.fits")
````
(You also can use absolute paths, but this is not recommended, as it leaks the directory structure.)

If you are having problems loading FITS files, please open another issue, so that we keep the different problems separate. I'm going to close this memory-leak issue.

**Closed by ericmandel** 2017-01-31 13:31 UTC
