### ISSUE TITLE
interactive menu not working from Jupyter notebooks

### ISSUE THREAD

**Issue by mgckind** [ericmandel/js9#23] opened 2016-09-22 03:23 UTC
Hi Eric,

I have been using js9-allinone files to display JS9 divs on lcoal jupyter notebooks. Up to v1.9 the menu (File, View, Zoom, etc.) was responding ok. When I use the files from master it doesn't respond anymore. The  <div> display the images fine, it is juts the menu is not responding. Not sure if related to the new styles in the menu but I haven't been able to trace it.  Any thoughts?

**Comment by ericmandel** [comment] 2016-09-22 03:49
@mgckind 

Hi Matias,

I did update the context menu code since v1.9 was released, so let me look into that tomorrow. I see I need a more formal test file for the allinone code, if it's being used.

**Comment by mgckind** [comment] 2016-09-22 04:13
I've found the commit,  26ee344ecded84f6bc6d4c8686f703d47df97843

After that, the menu stopped responding (in jupyter)

**Comment by ericmandel** [comment] 2016-09-22 18:24
(Documenting the fix before closing the issue)

I fixed the contextMenu problem and uploaded everything into GitHub. The cause is most unfortunate: the contextMenu code was upgraded in July, and the new "immediately invoked function expression" did not work with Jupyter, which did not see $ as jQuery and therefore did not add the contextMenu function to $. So I hacked the jquery.contextMenu.js code to use the old style IIFE and it now works in Jupyter.

As you pointed out, there is a Jupyter issue related to the problem:

https://github.com/jupyter/notebook/issues/749

but no clear path from that issue thread, so we’ll have to keep an eye on the Jupyter support as Jupyter evolves. Hopefully, the Jupyter developers will decide on some stable 'best practices' that don’t require a lot of Jupyter-specific coding ...

**Closed by ericmandel** 2016-09-22 18:24 UTC
